version: '3.4'

services:
  drui:
    image: localhost/drui:0.2.2
    container_name: drui
    restart: always
    read_only: true
    environment:
      DRUI_REGISTRY_ENDPOINT: http://distribution:5000
      DRUI_REGISTRY_PULL_ENDPOINT: http://host.docker.internal:5000
      DRUI_MARK_OFFICIAL_PREFIX: library
      DRUI_METRICS_ENABLE: true
    ports:
      - 8000:8000
    security_opt:
      - no-new-privileges:true
    depends_on:
      - distribution
  distribution:
      image: distribution/distribution:3.0.0
      container_name: distribution
      restart: always
      read_only: true
      ports:
        - 5000:5000
      volumes:
        - data:/var/lib/registry
      security_opt:
        - no-new-privileges:true

volumes:
  data:
    name: distribution_data
